# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜名')),
                ('point', models.IntegerField(default=0, verbose_name='点赞数')),
                ('main_meal', models.CharField(max_length=500, verbose_name='主材')),
                ('assist_meal', models.CharField(max_length=500, verbose_name='辅材')),
                ('others', models.CharField(max_length=500, verbose_name='其他')),
                ('food_method', models.CharField(max_length=1000, verbose_name='做法')),
                ('image_name', models.CharField(max_length=100, verbose_name='图片')),
                ('food_kind', models.CharField(max_length=20, verbose_name='菜系')),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
