# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=11, verbose_name='账号')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('visits', models.IntegerField(default=0, verbose_name='访问量')),
            ],
            options={
                'db_table': 'car_user',
            },
        ),
    ]
