# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarUser',
        ),
    ]
