# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginAndreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musci_liuyan', models.TextField(default='null')),
                ('sport_liuyan', models.TextField(default='null')),
                ('car_liuyan', models.TextField(default='null')),
                ('movie_liuyan', models.TextField(default='null')),
                ('food_liuyan', models.TextField(default='null')),
                ('book_liuyan', models.TextField(default='null')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('totaluser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginAndreg.TotalUser')),
            ],
            options={
                'db_table': 'userliuyan',
            },
        ),
    ]
