# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.CharField(max_length=100, verbose_name='性别')),
                ('magnum_opus', models.CharField(max_length=100, verbose_name='代表作')),
                ('a_decs', models.TextField(verbose_name='作者简介')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='书名')),
                ('publish', models.CharField(max_length=100, verbose_name='出版社')),
                ('a_decs', models.TextField(verbose_name='图书简介')),
                ('sort', models.CharField(max_length=50, verbose_name='类别')),
                ('content', models.TextField(verbose_name='内容')),
                ('up_time', models.DateTimeField(verbose_name='上架时间')),
                ('stow_number', models.IntegerField(default=0, verbose_name='收藏数')),
                ('read_number', models.IntegerField(default=0, verbose_name='阅读数')),
                ('imgs_src', models.CharField(max_length=200, verbose_name='图片地址')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookweb.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
